"""Seed / upsert semantic entities for WAR_ROM analytics layer."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from sqlalchemy import text
from sqlalchemy.engine import Engine

from analytics.db import apply_migrations, get_engine

ENTITIES: list[dict[str, Any]] = [
    {
        "entity_code": "checks",
        "entity_name": "Чеки",
        "business_description": "Документы розничных чеков ККМ",
        "c1_metadata_pattern": "Документ.ЧекККМ / Document156",
        "source_tables": "dbo._Document156",
        "grain": "один документ чека",
        "business_keys": "_IDRRef,_Number,_Date_Time",
        "date_field": "_Date_Time (YearOffset 2000)",
        "store_field": "prefix(_Number) Python map",
        "warehouse_field": None,
        "item_field": None,
        "status": "confirmed",
        "validation_status": "validated_sql",
        "owner": "warroom-analytics",
        "notes": "Fld4036: 1=возврат, 2=продажа; Fld4030 сумма",
    },
    {
        "entity_code": "check_lines",
        "entity_name": "Строки чеков",
        "business_description": "Товарные строки розничного чека",
        "c1_metadata_pattern": "ТЧ товаров чека VT4039",
        "source_tables": "dbo._Document156_VT4039",
        "grain": "строка чека",
        "business_keys": "_Document156_IDRRef,_KeyField",
        "date_field": "via parent document",
        "store_field": "via parent _Number",
        "warehouse_field": None,
        "item_field": "_Fld4041RRef → _Reference58",
        "status": "confirmed",
        "validation_status": "validated_sql",
        "owner": "warroom-analytics",
        "notes": "Fld4042 qty, Fld4048 sum, Fld4054 sum VAT",
    },
    {
        "entity_code": "retail_sales",
        "entity_name": "Розничные продажи",
        "business_description": "Чеки продажи (_Fld4036=2)",
        "c1_metadata_pattern": "Документ.ЧекККМ",
        "source_tables": "dbo._Document156",
        "grain": "документ продажи",
        "business_keys": "_IDRRef",
        "date_field": "_Date_Time",
        "store_field": "prefix(_Number)",
        "warehouse_field": None,
        "item_field": None,
        "status": "confirmed",
        "validation_status": "validated_sql",
        "owner": "warroom-analytics",
        "notes": None,
    },
    {
        "entity_code": "returns",
        "entity_name": "Возвраты",
        "business_description": "Чеки возврата (_Fld4036=1)",
        "c1_metadata_pattern": "Документ.ЧекККМ",
        "source_tables": "dbo._Document156",
        "grain": "документ возврата",
        "business_keys": "_IDRRef",
        "date_field": "_Date_Time",
        "store_field": "prefix(_Number)",
        "warehouse_field": None,
        "item_field": None,
        "status": "confirmed",
        "validation_status": "validated_sql",
        "owner": "warroom-analytics",
        "notes": None,
    },
    {
        "entity_code": "payments_by_shift_close",
        "entity_name": "Оплаты по закрытиям смен",
        "business_description": "Формы оплаты только на уровне закрытия смены",
        "c1_metadata_pattern": "Документ закрытия смены + VT2299",
        "source_tables": "dbo._Document119,dbo._Document119_VT2299,dbo._Reference89",
        "grain": "строка оплаты смены",
        "business_keys": "_Document119_IDRRef,_Fld2301RRef",
        "date_field": "_Document119._Date_Time",
        "store_field": "prefix(_Number)",
        "warehouse_field": None,
        "item_field": None,
        "status": "confirmed",
        "validation_status": "validated_sql",
        "owner": "warroom-analytics",
        "notes": "НЕ привязывать к individual чеку без доказанной связи",
    },
    {
        "entity_code": "stores",
        "entity_name": "Торговые точки",
        "business_description": "Магазины по префиксу номера документа",
        "c1_metadata_pattern": "prefix map + candidate _Reference64",
        "source_tables": "Python store_prefix_map; dbo._Reference64 (candidate)",
        "grain": "магазин",
        "business_keys": "prefix / _Code",
        "date_field": None,
        "store_field": "store_name",
        "warehouse_field": None,
        "item_field": None,
        "status": "confirmed_partial",
        "validation_status": "prefix_confirmed_ref64_candidate",
        "owner": "warroom-analytics",
        "notes": "Неизвестные префиксы → «Неизвестный магазин / требуется mapping»",
    },
    {
        "entity_code": "warehouses",
        "entity_name": "Склады",
        "business_description": "Склады из справочника / регистра остатков",
        "c1_metadata_pattern": "_Reference76",
        "source_tables": "dbo._Reference76",
        "grain": "склад",
        "business_keys": "_IDRRef",
        "date_field": None,
        "store_field": "warehouse_to_store heuristic",
        "warehouse_field": "_Description",
        "item_field": None,
        "status": "candidate",
        "validation_status": "requires_1c_signoff",
        "owner": "warroom-analytics",
        "notes": "Mapping склад→магазин эвристический",
    },
    {
        "entity_code": "products",
        "entity_name": "Номенклатура",
        "business_description": "Справочник номенклатуры",
        "c1_metadata_pattern": "_Reference58",
        "source_tables": "dbo._Reference58",
        "grain": "номенклатура",
        "business_keys": "_IDRRef",
        "date_field": None,
        "store_field": None,
        "warehouse_field": None,
        "item_field": "_Description",
        "status": "confirmed",
        "validation_status": "validated_sql_sample",
        "owner": "warroom-analytics",
        "notes": "Связь с VT4039._Fld4041RRef подтверждена на выборке",
    },
    {
        "entity_code": "cost_of_sales",
        "entity_name": "Себестоимость продаж",
        "business_description": "Кандидат себестоимости из регистра накопления",
        "c1_metadata_pattern": "_AccumRg6691 / _AccumRg6738",
        "source_tables": "dbo._AccumRg6691,dbo._AccumRg6738",
        "grain": "движение регистра / день×магазин",
        "business_keys": "_Period,_Fld6692RRef,_RecorderRRef",
        "date_field": "_Period",
        "store_field": "_Fld6692RRef→_Reference64",
        "warehouse_field": None,
        "item_field": "candidate fields",
        "status": "candidate",
        "validation_status": "requires_final_1c_reconciliation",
        "owner": "warroom-analytics",
        "notes": "Fld6708 кандидат COGS; требуется финальная сверка с 1С",
    },
    {
        "entity_code": "stock_balances",
        "entity_name": "Остатки",
        "business_description": "Обороты/остатки по складу (кандидат)",
        "c1_metadata_pattern": "_AccumRg6601",
        "source_tables": "dbo._AccumRg6601,dbo._Reference76",
        "grain": "день×склад (агрегат движений)",
        "business_keys": "_Period,_Fld6603RRef",
        "date_field": "_Period",
        "store_field": "via warehouse map",
        "warehouse_field": "_Fld6603RRef",
        "item_field": "candidate",
        "status": "candidate",
        "validation_status": "requires_final_1c_reconciliation",
        "owner": "warroom-analytics",
        "notes": "Fld6607 qty, Fld6608 amount; не путать с выручкой",
    },
    {
        "entity_code": "writeoffs",
        "entity_name": "Списания",
        "business_description": "Кандидат списаний / корректировок _Document124",
        "c1_metadata_pattern": "Документ124 + VT2532",
        "source_tables": "dbo._Document124,dbo._Document124_VT2532",
        "grain": "документ / строка",
        "business_keys": "_IDRRef",
        "date_field": "_Date_Time",
        "store_field": "prefix(_Number)",
        "warehouse_field": None,
        "item_field": "VT line refs",
        "status": "candidate",
        "validation_status": "requires_1c_signoff",
        "owner": "warroom-analytics",
        "notes": "Тип по знаку суммы — эвристика",
    },
    {
        "entity_code": "transfers",
        "entity_name": "Перемещения",
        "business_description": "Кандидат перемещений _Document122",
        "c1_metadata_pattern": "Document122",
        "source_tables": "dbo._Document122",
        "grain": "документ",
        "business_keys": "_IDRRef",
        "date_field": "_Date_Time",
        "store_field": "prefix(_Number) if present",
        "warehouse_field": None,
        "item_field": None,
        "status": "candidate",
        "validation_status": "requires_1c_signoff",
        "owner": "warroom-analytics",
        "notes": None,
    },
    {
        "entity_code": "inventories",
        "entity_name": "Инвентаризации",
        "business_description": "Не выделен отдельный подтверждённый объект",
        "c1_metadata_pattern": "unknown",
        "source_tables": None,
        "grain": "unknown",
        "business_keys": None,
        "date_field": None,
        "store_field": None,
        "warehouse_field": None,
        "item_field": None,
        "status": "not_found",
        "validation_status": "metric_not_found",
        "owner": "warroom-analytics",
        "notes": "Частично пересекается с кандидатом _Document124",
    },
    {
        "entity_code": "inventory_differences",
        "entity_name": "Излишки и недостачи",
        "business_description": "Не выделен подтверждённый отдельный источник",
        "c1_metadata_pattern": "unknown",
        "source_tables": None,
        "grain": "unknown",
        "business_keys": None,
        "date_field": None,
        "store_field": None,
        "warehouse_field": None,
        "item_field": None,
        "status": "not_found",
        "validation_status": "metric_not_found",
        "owner": "warroom-analytics",
        "notes": None,
    },
    {
        "entity_code": "price_history",
        "entity_name": "История цен",
        "business_description": "Тип цены в чеке _Fld4016RRef; справочник не сопоставлен",
        "c1_metadata_pattern": "_Fld4016RRef / _Reference92?",
        "source_tables": "dbo._Document156._Fld4016RRef",
        "grain": "чек",
        "business_keys": "_Fld4016RRef",
        "date_field": "_Date_Time",
        "store_field": None,
        "warehouse_field": None,
        "item_field": None,
        "status": "candidate",
        "validation_status": "requires_mapping",
        "owner": "warroom-analytics",
        "notes": "JOIN к _Reference92 = 0 совпадений на выборке",
    },
    {
        "entity_code": "discounts",
        "entity_name": "Скидки",
        "business_description": "Не найден подтверждённый ресурс скидок",
        "c1_metadata_pattern": "unknown",
        "source_tables": None,
        "grain": "unknown",
        "business_keys": None,
        "date_field": None,
        "store_field": None,
        "warehouse_field": None,
        "item_field": None,
        "status": "not_found",
        "validation_status": "metric_not_found",
        "owner": "warroom-analytics",
        "notes": None,
    },
    {
        "entity_code": "supplier_returns",
        "entity_name": "Возвраты поставщику",
        "business_description": "Не найден подтверждённый SQL-объект",
        "c1_metadata_pattern": "unknown",
        "source_tables": None,
        "grain": "unknown",
        "business_keys": None,
        "date_field": None,
        "store_field": None,
        "warehouse_field": None,
        "item_field": None,
        "status": "not_found",
        "validation_status": "metric_not_found",
        "owner": "warroom-analytics",
        "notes": None,
    },
]


def seed_semantic_entities(engine: Engine | None = None) -> dict[str, int]:
    eng = engine or get_engine()
    apply_migrations(eng)
    now = datetime.now(timezone.utc).isoformat()
    upserted = 0
    with eng.begin() as conn:
        for e in ENTITIES:
            row = dict(e)
            row["updated_at"] = now
            conn.execute(
                text(
                    """
                    INSERT INTO analytics_semantic_entities
                    (entity_code, entity_name, business_description, c1_metadata_pattern, source_tables,
                     grain, business_keys, date_field, store_field, warehouse_field, item_field,
                     status, validation_status, owner, updated_at, notes)
                    VALUES
                    (:entity_code, :entity_name, :business_description, :c1_metadata_pattern, :source_tables,
                     :grain, :business_keys, :date_field, :store_field, :warehouse_field, :item_field,
                     :status, :validation_status, :owner, :updated_at, :notes)
                    ON CONFLICT(entity_code) DO UPDATE SET
                      entity_name=excluded.entity_name,
                      business_description=excluded.business_description,
                      c1_metadata_pattern=excluded.c1_metadata_pattern,
                      source_tables=excluded.source_tables,
                      grain=excluded.grain,
                      business_keys=excluded.business_keys,
                      date_field=excluded.date_field,
                      store_field=excluded.store_field,
                      warehouse_field=excluded.warehouse_field,
                      item_field=excluded.item_field,
                      status=excluded.status,
                      validation_status=excluded.validation_status,
                      owner=excluded.owner,
                      updated_at=excluded.updated_at,
                      notes=excluded.notes
                    """
                ),
                row,
            )
            upserted += 1
    return {"upserted": upserted}


def list_entities(engine: Engine | None = None) -> list[dict[str, Any]]:
    eng = engine or get_engine()
    apply_migrations(eng)
    with eng.connect() as conn:
        rows = conn.execute(
            text("SELECT * FROM analytics_semantic_entities ORDER BY entity_code")
        ).mappings().all()
    return [dict(r) for r in rows]
